### ISSUE TITLE
power from eBus

### ISSUE THREAD

**Issue by danielkucera** [slavikb/BaiMon#1]
Hi,

is there any reason why don't you power ESP from eBus?

**Comment by slavikb** [comment]
Just for safety. I was not sure that my boiler can provide enough current and was afraid to damage it.

**Comment by danielkucera** [comment]
I am thinking about powering my unit from the bus. This would also mean that I don't need to use optocoupling. In theory this should be possible, eBus should provide 50-100mA@20V which means 300-600mA@3V3 according to this: http://ebus-wiki.org/lib/exe/fetch.php/ebus/spec_prot_12_v1_3_1_e.pdf

Do you think it will work?

**Comment by slavikb** [comment]
I am not a great specialist in electronics, so i may just guess. 
Looks workable, given that ESP8266 drains max 170mA during transmit.
In this case you will need 3V voltage stabilizer, of course.

**Comment by EUA** [comment]
FYI: I tried to power my ESP8266 with EBUS 5v.
**I got boiler resets at ignition time**.
Than add step-down regulator ($1-2 USD ones sold at AliExpress, stamp size).
That drop +5V bus to 3.3v, efficiently.
Looks like my boiler working without issue on this setup.
But if you decide to use such a step-down regulator you better to use pin 6(?) which has +24v.
I can't use it since I have no 6p6c RJ11 but 4p4c one.

**Comment by danielkucera** [comment]
@EUA , thanks for hints. I'm running it with a stepdown regulator for about a year now a had no troubles so far. Not sure what connector are you talking about but my eBus provides about 20V when idle.

**Comment by LordMike** [comment]
@EUA do you have a wiring schematic for powering a 3V3 ESP8266 from the eBUS line?

**Comment by slavikb** [comment]
Unfortunately, not. AFAIK, danielkucera had developed such device.

**Comment by LordMike** [comment]
Tagging @danielkucera to hear if he has a schematic. :)

**Comment by danielkucera** [comment]
@LordMike This is what I use: https://github.com/danielkucera/ebus-adapter

It works but the DC/DC regulator is squeaking and I didn't find out why so far. Maybe it would be worth try to replace the regulator module with a different chip.

**Comment by LordMike** [comment]
Could I trouble you to add a few lines to the repo, which file is what etc.. ?

I'm not familiar with a few of the filetypes, and it seems like there's a mix of a v1 and v2 ?

**Comment by danielkucera** [comment]
It's still quite raw repo. Just use KiCAD and open `wiring.pro`

**Comment by EUA** [comment]
@LordMike , nope. I don't have schematics. Just make it on breadboard.
